---
- name: FIrst Playbook
  hosts: localhost
  become: yes
  tasks:
  - name: my first server
    apt:
     name: nginx
     state: latest

  - name: my second server
    apt:
     name: tree
     state: latest
...