---
- name: Simple Web Server Setup
  hosts: all
  become: yes  

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'  

    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    - name: Start Apache and enable it on boot
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create index.html
      copy:
        content: "<html><body><h1>Hello,& Welcome to OMKAR's github!</h1></body></html>"
        dest: /var/www/html/index.html
...
